---
title: "qemistree_output.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load required packages
library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(vegan)
```

```{r}
#load data
load(".RData")
```

# vegan tutorial from: https://peat-clark.github.io/BIO381/veganTutorial.html

```{r}
#Simpson's 1-D Index of Diversity for each site. # closer to 1 = greater diversity

simpson <- diversity(heat, index = "simpson")
simpson
```

```{r}
shannon <- diversity(heat) # note that Shannon's is default
shannon #Typically ranges from 1.5 - 3.4, higher = more diverse
```

```{r}
# lets compare the two
par(mfrow = c(1, 2))  # use par to generate panels with 1 row of 2 graphs
hist(simpson)
hist(shannon)
```

```{r}
par(mfrow = c(1, 2))
bray = vegdist(heat, "bray") 
gower = vegdist(heat, "gower")
hist(bray, xlim = range(0.0,1.0))
hist(gower, xlim = range(0.0,1.0))
```

```{r}
#convert row names to first column
heat2 <- heat
heat2 <- tibble::rownames_to_column(heat2, "id")
View(heat2)
```

```{r}
#convert heat data from wide to long

# The arguments to gather():
# - data: Data object
# - key: Name of new key column (made from names of data columns)
# - value: Name of new value column
# - ...: Names of source columns that contain values
# - factor_key: Treat the new key column as a factor (instead of character vector)

heat_long <- gather(heat2, coralID, peak, -id, factor_key = TRUE)
View(heat_long)
```

```{r}
#combine heat2 and siri dataframes 
all <- merge(heat2, siri, by="id")
View(all)
```

```{r}
#transform total data into longform 
all_long <- gather(all, coralID, peak, X9GT28.mzXML.Peak.area:X2GT1.mzXML.Peak.area, factor_key = TRUE)
View(all_long)
```

# CHAT WITH KEVIN
# polarity picking
# normalization (kevin used sample weight)
# zero inflation correction
# PCA 
# PERMANOVA
# PLS-DA: can extract VIPs (not necessarily useful unless you have two groups)
# t-test validation with FDR 
# MetaboAnalyst on VIPs (kind of like a WGCNA)
# overrepresentation analysis 


#Diversity analysis from paper

```{r}
#create new heat dataset for diversity analysis
heat_clean2 <- heat_clean 

#change first column into row names
heat_clean2 <- heat_clean2[,-1]
rownames(heat_clean2) <- heat_clean[,1]

#flip rows and columns
heat_clean2 <- t(heat_clean2)
heat_clean2 <- as.data.frame(heat_clean2)

#make rownames a column
heat_clean2 <- tibble::rownames_to_column(heat_clean2, "filename")

#merge with metadata
heat_clean2 <- merge(heat_clean2, meta, by="filename")
heat_clean2$ATTRIBUTE_acclimation <- as.factor(heat_clean2$ATTRIBUTE_acclimation)
heat_clean2 <- subset(heat_clean2, !is.na(ATTRIBUTE_acclimation))
```

```{r}
#standardize by dry weight 
info <- heat_clean2[ ,c(1,346:349)]
heat_clean2 <- heat_clean2[ ,c(2:345)]/heat_clean2$ATTRIBUTE_dryweight
heat_clean2 <- cbind(info, heat_clean2)
```

```{r}
div<-as.matrix(heat_clean2[ ,c(6:349)])
list<-heat_clean2 %>% select(ATTRIBUTE_acclimation, ATTRIBUTE_genotype)
```

```{r}
#run diversity analyses
shannon<-as.data.frame(diversity(div, index = "shannon", MARGIN = 1, base = exp(1)));names(shannon)[1]<-"shannon"
richness<-as.data.frame(div)%>%mutate(richness=rowSums(.!=0))%>%select(richness)
metrics<-bind_cols(list,shannon,richness)%>%mutate(evenness=shannon/log(richness))
View(metrics)
```

```{r}
#this doesn't work but I might not need it? 
leveneTest(shannon~ATTRIBUTE_acclimation,data=metrics);t.test(shannon~ATTRIBUTE_acclimation,data=metrics)
leveneTest(richness~ATTRIBUTE_acclimation,data=metrics);t.test(richness~ATTRIBUTE_acclimation,data=metrics)
leveneTest(evenness~ATTRIBUTE_acclimation,data=metrics);t.test(evenness~ATTRIBUTE_acclimation,data=metrics)
#Error in t.test.formula(shannon ~ ATTRIBUTE_acclimation, data = metrics) : grouping factor must have exactly 2 levels
```

#Make boxplots
```{r}
#Diversity
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

a<-ggplot(metrics, aes(x = ATTRIBUTE_acclimation, y = shannon))+
     geom_boxplot(aes(ATTRIBUTE_acclimation,shannon,fill=ATTRIBUTE_acclimation))+
     geom_jitter(aes(ATTRIBUTE_acclimation,shannon),width=0.02,alpha=0.2)+
     theme_classic(base_size=12)+
     ylab("Shannon's Diversity Index")+
     xlab("Acclimation Treatment")+
     theme(legend.position="none")+
  stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = 1.3, label.y = 5)
a
```

```{r}
#Richness
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

b<-ggplot(metrics, aes(x = ATTRIBUTE_acclimation, y = richness))+
  geom_boxplot(aes(ATTRIBUTE_acclimation,richness,fill=ATTRIBUTE_acclimation))+
     geom_jitter(aes(ATTRIBUTE_acclimation,richness),width=0.02,alpha=0.2)+
     theme_classic(base_size=12)+
     ylab("Richness")+
     xlab("Acclimation Treatment")+
     theme(legend.position="none")+
  stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = 1.3, label.y = 300)
b
```

```{r}
#Evenness
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

c<-ggplot(metrics, aes(x = ATTRIBUTE_acclimation, y = evenness))+
  geom_boxplot(aes(ATTRIBUTE_acclimation,evenness,fill=ATTRIBUTE_acclimation))+
     geom_jitter(aes(ATTRIBUTE_acclimation,evenness),width=0.02,alpha=0.2)+
     theme_classic(base_size=12)+
     ylab("Evenness")+
     xlab("Acclimation Treatment")+
     theme(legend.position="none",legend.key.size = unit(0.5,"cm"))+
  stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = 4, label.y = 0.95)
c
```
```{r}
grid.arrange(a, b, c, nrow = 1)
```

```{r}
#Diversity
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

d<-ggplot(metrics, aes(x = ATTRIBUTE_genotype, y = shannon))+
     geom_boxplot(aes(ATTRIBUTE_genotype,shannon,fill=ATTRIBUTE_genotype))+
     geom_jitter(aes(ATTRIBUTE_genotype,shannon),width=0.02,alpha=0.2)+
     theme_classic(base_size=10)+
     ylab("Shannon's Diversity Index")+
     xlab("Genotype")+
     theme(legend.position="none")+
  stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = "BY", label.y = 5)
d
```

```{r}
#Richness
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

e<-ggplot(metrics, aes(x = ATTRIBUTE_genotype, y = richness))+
  geom_boxplot(aes(ATTRIBUTE_genotype,richness,fill=ATTRIBUTE_genotype))+
     geom_jitter(aes(ATTRIBUTE_genotype,richness),width=0.02,alpha=0.2)+
     theme_classic(base_size=10)+
     ylab("Richness")+
     xlab("Genotype")+
     theme(legend.position="none")+
  stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = "BY", label.y = 300)
e
```

```{r}
#Evenness
MinMeanSEMMax <- function(x) {
  v <- c(min(x), mean(x) - sd(x)/sqrt(length(x)), mean(x), mean(x) + sd(x)/sqrt(length(x)), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

f<-ggplot(metrics, aes(x = ATTRIBUTE_genotype, y = evenness))+
  geom_boxplot(aes(ATTRIBUTE_genotype,evenness,fill=ATTRIBUTE_genotype))+
     geom_jitter(aes(ATTRIBUTE_genotype,evenness),width=0.02,alpha=0.2)+
     theme_classic(base_size=10)+
     ylab("Evenness")+
     xlab("Genotype")+
     theme(legend.position="none",legend.key.size = unit(0.5,"cm"))+
  stat_compare_means(aes(label = paste0("p = ", ..p.format..)), label.x = "BY", label.y = 0.95)
f
```

```{r}
grid.arrange(d, e, f, nrow = 1)
```





















.





































.