---
title: "comparisons"
output: html_document
date: '2023-09-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Code modified from https://github.com/soswift/waimea_marine/

```{r load packages, warning=FALSE, message=FALSE}
library(BiocManager)
#BiocManager::install('phyloseq')
library('phyloseq')
library(data.table)
library(dplyr)
library(tidyr)
library(vegan)
library(devtools)
#install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis") 
library(pairwiseAdonis) 
library(cowplot)
library(UpSetR)
library(naniar)
library(qdap)
library(fitdistrplus)
library(factoextra)
```

#PERMANOVAS

```{r permanovas on metabolites}
# run permanovas on metabolites, modeling by sample type, site, and the interaction
#chem_anova_all <-
  #do_permanova(
    #chem_phy,
    #var_name = "sample_type*site_name",
    #dist_obj = chem_dist$bray,
    #description = "All microbe samples"
  #)
#write.csv(chem_anova_all,
          #"output/permanova/all_metabolite_permanova_by_site_type.csv")
```

```{r PERMANOVA for all compounds}
#turn rownnames into column
tagg_all_filt2 <- as.data.frame(tagg_all_filt)
tagg_all_filt2 <- tagg_all_filt2 %>% mutate_if(is.character,as.numeric) #make sure data columns are numberic

tagg_all_filt2$ATTRIBUTE_sampleID <- rownames(tagg_all_filt2)

#add metadata to tagg_all_filt dataframe 
tagg_all_filt2 <- merge(tagg_all_filt2, meta2, by="ATTRIBUTE_sampleID", all = FALSE)

#View(tagg_all_filt2)

#https://github.com/AHuffmyer/EarlyLifeHistory_Energetics/blob/master/Mcap2020/Scripts/TagSeq/Genome_V3/1_WGCNA_Mcap_V3.Rmd
scaled_test <-prcomp(tagg_all_filt2[c(2:333)], scale=TRUE, center=TRUE)
fviz_eig(scaled_test)

# scale data
vegan <- scale(tagg_all_filt2[c(2:333)])

# PerMANOVA: acclimation
permanova_acc <-adonis2(vegan ~ ATTRIBUTE_acclimation, data = tagg_all_filt2, method='eu')
permanova_acc 

# PerMANOVA: genotype
permanova_gen <-adonis2(vegan ~ ATTRIBUTE_genotype, data = tagg_all_filt2, method='eu')
permanova_gen 
```

```{r PERMANOVA for key compounds}
#use agg_all_keycomps file: already has metadata 
#make sure data columns are being read as factor
agg_all_keycomps$ATTRIBUTE_acclimation <- as.factor(agg_all_keycomps$ATTRIBUTE_acclimation)
agg_all_keycomps$ATTRIBUTE_genotype <- as.factor(agg_all_keycomps$ATTRIBUTE_genotype)

#https://github.com/AHuffmyer/EarlyLifeHistory_Energetics/blob/master/Mcap2020/Scripts/TagSeq/Genome_V3/1_WGCNA_Mcap_V3.Rmd
scaled_test_kc <-prcomp(agg_all_keycomps[c(5:9)], scale=TRUE, center=TRUE)
fviz_eig(scaled_test_kc)

# scale data
vegan_kc <- scale(agg_all_keycomps[c(5:9)])

# PerMANOVA: acclimation
permanova_kc_acc <-adonis2(vegan_kc ~ ATTRIBUTE_acclimation, data = agg_all_keycomps, method='eu')
permanova_kc_acc

# PerMANOVA: genotype
permanova_kc_gen <-adonis2(vegan_kc ~ ATTRIBUTE_genotype, data = agg_all_keycomps, method='eu')
permanova_kc_gen 
```

```{r PERMANOVA for grey module}
#use agg_all_grey file: already has metadata 
#make sure data columns are being read as factor
agg_all_grey$ATTRIBUTE_acclimation <- as.factor(agg_all_grey$ATTRIBUTE_acclimation)
agg_all_grey$ATTRIBUTE_genotype <- as.factor(agg_all_grey$ATTRIBUTE_genotype)

#https://github.com/AHuffmyer/EarlyLifeHistory_Energetics/blob/master/Mcap2020/Scripts/TagSeq/Genome_V3/1_WGCNA_Mcap_V3.Rmd
scaled_test_grey <-prcomp(agg_all_grey[c(5:16)], scale=TRUE, center=TRUE)
fviz_eig(scaled_test_grey)

# scale data
vegan_grey <- scale(agg_all_grey[c(5:16)])

# PerMANOVA: acclimation
permanova_grey_acc <-adonis2(vegan_grey ~ ATTRIBUTE_acclimation, data = agg_all_grey, method='eu')
permanova_grey_acc

# PerMANOVA: genotype
permanova_grey_gen <-adonis2(vegan_grey ~ ATTRIBUTE_genotype, data = agg_all_grey, method='eu')
permanova_grey_gen 
```

```{r PERMANOVA for aaa}
#use agg_all_aaa file: already has metadata 
#make sure data columns are being read as factor
agg_all_aaa$ATTRIBUTE_acclimation <- as.factor(agg_all_aaa$ATTRIBUTE_acclimation)
agg_all_aaa$ATTRIBUTE_genotype <- as.factor(agg_all_aaa$ATTRIBUTE_genotype)

#https://github.com/AHuffmyer/EarlyLifeHistory_Energetics/blob/master/Mcap2020/Scripts/TagSeq/Genome_V3/1_WGCNA_Mcap_V3.Rmd
scaled_test_aaa <-prcomp(agg_all_aaa[c(5:6)], scale=TRUE, center=TRUE)
fviz_eig(scaled_test_aaa)

# scale data
vegan_aaa <- scale(agg_all_aaa[c(5:6)])

# PerMANOVA: acclimation
permanova_aaa_acc <-adonis2(vegan_aaa ~ ATTRIBUTE_acclimation, data = agg_all_aaa, method='eu')
permanova_aaa_acc

# PerMANOVA: genotype
permanova_aaa_gen <-adonis2(vegan_aaa ~ ATTRIBUTE_genotype, data = agg_all_aaa, method='eu')
permanova_aaa_gen 
```

```{r PERMANOVA for subclass Amino acids}
#use agg_amino file: already has metadata 
#make sure data columns are being read as factor
agg_amino$ATTRIBUTE_acclimation <- as.factor(agg_amino$ATTRIBUTE_acclimation)
agg_amino$ATTRIBUTE_genotype <- as.factor(agg_amino$ATTRIBUTE_genotype)

#https://github.com/AHuffmyer/EarlyLifeHistory_Energetics/blob/master/Mcap2020/Scripts/TagSeq/Genome_V3/1_WGCNA_Mcap_V3.Rmd
scaled_test_amino <-prcomp(agg_amino[c(5:39)], scale=TRUE, center=TRUE)
fviz_eig(scaled_test_amino)

# scale data
vegan_amino <- scale(agg_amino[c(5:39)])

# PerMANOVA: acclimation
permanova_amino_acc <-adonis2(vegan_amino ~ ATTRIBUTE_acclimation, data = agg_amino, method='eu')
permanova_amino_acc

# PerMANOVA: genotype
permanova_amino_gen <-adonis2(vegan_amino ~ ATTRIBUTE_genotype, data = agg_amino, method='eu')
permanova_amino_gen 
```

#Upset Plots 
  
```{r select out new datafram upset_long}
#just to make my life easier
upset_long <- all_long2 %>% dplyr::select(c('id', 'ATTRIBUTE_acclimation', 'ATTRIBUTE_genotype', 'peak_stand'))

upset_long$id <- as.character(euler_acc$id)
upset_long$ATTRIBUTE_acclimation <- as.character(upset_long$ATTRIBUTE_acclimation)
upset_long$ATTRIBUTE_genotype <- as.character(upset_long$ATTRIBUTE_genotype)

#convert peak_stand to TRUE/FALSE column for compound presence
upset_long <- upset_long %>% mutate_if(is.numeric,as.logical)
#convert to 0 for FALSE and 1 for TRUE (could probably do this in one step instead of two)
upset_long$peak_stand <- as.integer(as.logical(upset_long$peak_stand))
#View(upset_long)
```

```{r format upset_acc for plotting}
upset_acc <- upset_long %>% dplyr::select(c('id', 'ATTRIBUTE_acclimation', 'peak_stand'))

upset_acc <- upset_acc[!upset_acc$peak_stand == 0, ] #remove data indicating that a compound doesn't exist: we only care about instances where it does 

upset_acc <- upset_acc %>% dplyr::select(c('id', 'ATTRIBUTE_acclimation')) #remove peak_stand column since it is now superfluous 

upset_acc <- upset_acc %>% dplyr::distinct() #remove duplicate rows 

upset_acc <- with(upset_acc, termco(ATTRIBUTE_acclimation, id, c("1", "2", "3", "4", "5")))[[1]][,-2] #use qdap to spread acclimation treatment data into five boolean columns (https://stackoverflow.com/questions/25347739/r-convert-factor-column-to-multiple-boolean-columns)

#View(upset_acc)
#write.csv(upset_acc,"upset_acc.csv")
```

```{r format upset_gen for plotting}
upset_gen <- upset_long %>% dplyr::select(c('id', 'ATTRIBUTE_genotype', 'peak_stand'))

upset_gen <- upset_gen[!upset_gen$peak_stand == 0, ] #remove data indicating that a compound doesn't exist: we only care about instances where it does 

upset_gen <- upset_gen %>% dplyr::select(c('id', 'ATTRIBUTE_genotype')) #remove peak_stand column since it is now superfluous 

upset_gen <- upset_gen %>% dplyr::distinct() #remove duplicate rows 

upset_gen <- with(upset_gen, termco(ATTRIBUTE_genotype, id, c("AZ", "BY", "CX", "DW", "EV", "FU", "GT", "HS", "IR", "JQ")))[[1]][,-2] #use qdap to spread genotype data into five boolean columns (https://stackoverflow.com/questions/25347739/r-convert-factor-column-to-multiple-boolean-columns)

#View(upset_gen)
#write.csv(upset_gen,"upset_gen.csv")
```

```{r basic acclimation upset plot}
upset(upset_acc, order.by = "freq")
```

```{r basic genotype upset plot}
upset(upset_gen, sets = c("AZ", "BY", "CX", "DW", "EV", "FU", "GT", "HS", "IR", "JQ"), order.by = "freq")
```

#extract lists of compound intersections (i.e. data from upset plots)

```{r extract intersections by acclimation}
#https://stackoverflow.com/questions/65027133/extract-intersection-list-from-upset-object
#use upset_acc

upsetacc_with_intersection <- upset_acc %>%
  unite(col = "intersection", -c("id"), sep = "")

# List of intersections and their entries
compoundlist_acc <- upsetacc_with_intersection %>%
  group_by(intersection) %>%
  summarise(list = list(id)) %>%
  mutate(list = setNames(list, intersection)) %>%
  pull(list)

capture.output(compoundlist_acc, file = "compoundlist_acc.txt")
```

```{r extract intersections by genotype}
#https://stackoverflow.com/questions/65027133/extract-intersection-list-from-upset-object
#use upset_gen

upsetgen_with_intersection <- upset_gen %>%
  unite(col = "intersection", -c("id"), sep = "")

# List of intersections and their entries
compoundlist_gen <- upsetgen_with_intersection %>%
  group_by(intersection) %>%
  summarise(list = list(id)) %>%
  mutate(list = setNames(list, intersection)) %>%
  pull(list)

capture.output(compoundlist_gen, file = "compoundlist_gen.txt")
```

```{r merge lists with metadata on compounds}
#reformat txt files in excel and reimport to r 
#(I'm sure there's a better way to do this, oh well)

compoundlist_acc <- read.csv("compoundlist_acc.csv")
compoundlist_acc$acclimation <- as.character(compoundlist_acc$acclimation)

compoundlist_gen <- read.csv("compoundlist_gen.csv")

modblue2 <- read.csv("modblue2.csv")
modred2 <- read.csv("modred2.csv")
modyellow2 <- read.csv("modyellow2.csv")
modbrown2 <- read.csv("modbrown2.csv")
modturquoise2 <- read.csv("modturquoise2.csv")
modgrey2 <- read.csv("modgrey2.csv")

#modules2 <- rbind(modblue2, modred2, modyellow2, modbrown2, modturquoise2, modgrey2)
modules2 <- dplyr::bind_rows(modblue2, modred2, modyellow2, modbrown2, modturquoise2, modgrey2)
#View(modules2)

compoundlist_acc <- left_join(compoundlist_acc, modules2, by = join_by(id == id))
#View(compoundlist_acc)

compoundlist_gen <- left_join(compoundlist_gen, modules2, by = join_by(id == id))
#View(compoundlist_gen)

compoundlist_acc <- left_join(compoundlist_acc, siri, by = join_by(id == id))
#View(compoundlist_acc)

compoundlist_gen <- left_join(compoundlist_gen, siri, by = join_by(id == id))
#View(compoundlist_gen)
```

```{r}
write.csv(compoundlist_acc, "output/compoundlist_acc_info.csv")
write.csv(compoundlist_gen, "output/compoundlist_gen_info.csv")
```

































.