---
title: "reject"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#remove date and initial columns from dataset
all_long2 <- all_long2[ -c(22:26)]
```

```{r}
#reformat all_long2 dataframe so compounds are listed as column headers
all_wide <- spread(all_long2, id, peak_stand)

#add 1000 to all variables to account for 0 values and log normalization
all_wide2 <- log((all_wide[21:ncol(all_wide)] + 1000), 2)
all_wide_norm <- cbind(all_wide[1:20], all_wide2)

View(all_wide_norm)
```

```{r}
#make sure data is numeric
cols <- c(21:ncol(all_wide_norm))
all_wide_norm[cols] <- lapply(all_wide_norm[cols], as.numeric)

#pca attempt 1
pca1 <- prcomp(all_wide_norm[c(21:ncol(all_wide_norm))], center = TRUE, scale. = TRUE, na.rm = TRUE)
summary(pca1)
```


```{r}
#pca of just the heat data out of curiosity
pca2 <- prcomp(heat_clean[2:ncol(heat_clean)], scale. = TRUE)
summary(pca2)

#okay that seems to work so I have to combine this format with the metadata maybe? 
```


```{r}
#practice with Iris dataset
cal.ind = c(1:25, 51:75, 101:125)
val.ind = c(26:50, 76:100, 126:150)

Xc = iris[cal.ind, 1:4]
Xv = iris[val.ind, 1:4]

cc.all = iris[cal.ind, 5]
cv.all = iris[val.ind, 5]
```

```{r}
show(cc.all)
```

```{r}
cc.vir = cc.all == "virginica"
cv.vir = cv.all == "virginica"
```

```{r}
m.all = plsda(Xc, cc.all, 3, cv = 1)
m.vir = plsda(Xc, cc.vir, 3, cv = 1, classname = "virginica")
```

```{r}
summary(m.all)
```