---
title: "selecteddata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
#load required libraries
library(tidyr)
library("reshape")
library(plyr)
library(dplyr)
library(ggplot2)
library("arsenal")
library("Rmisc")
library(gridExtra)
library(ggpubr)
library(factoextra)
library(ggplot2)
library(RColorBrewer)
library(lme4)
library(lmerTest)
library(car)
library(effects)
library(ggfortify)
library(cowplot)
library(vegan)
library(corrr)
library(ggcorrplot)
library(GGally)
library(broom)
library(cowplot)
library(RVAideMemoire)
library(arsenal)
library(patchwork)
library(tidyr)
library(ggrepel)
library(randomForest)
library("janitor")
library(caret)
library(varImp)
```

```{r}
#packages from paper 
library(readxl)
library(cowplot)
library(RColorBrewer)
library(janitor)
library(viridis)
library(vegan)
library(car)
library(magicfor)
library(grid)
library(factoextra)
library(egg)
```

```{r}
#select out only top two most important direct parents: 
#lineolic_acids_and_derivatives and organosulfonic_acids
agg_parent_norm_known3 <- agg_parent_norm_known2 %>% dplyr::select(1:4, 33, 46, 58)
```

```{r}
#PCA of important direct parents
pca_vip <- prcomp(agg_parent_norm_known3[c(5:6)], scale. = TRUE, center = TRUE)
summary(pca_vip)

#calculate eigenvalues 
fviz_eig(pca_vip)
```

```{r}
#prepare for plotting 
coral_info_vip <- agg_parent_norm_known3[c(2,3)]

pca_data_vip <- pca_vip %>%
  augment(coral_info_vip) %>%
  group_by(attribute_acclimation, attribute_genotype) %>%
  mutate(PC1.mean = mean(.fittedPC1),
         PC2.mean = mean(.fittedPC2))

pca.centroids.vip <- pca_data_vip %>%
  dplyr::select(attribute_acclimation, attribute_genotype, PC1.mean, PC2.mean) %>%
  dplyr::group_by(attribute_acclimation, attribute_genotype) %>%
  dplyr::summarise(PC1.mean = mean(PC1.mean), PC2.mean = mean(PC2.mean))
```

```{r}
#Examine PERMANOVA results

# scale data
vegan_vip <- scale(agg_parent_norm_known3[c(5:6)])

# PerMANOVA 
permanova_vip <- adonis(vegan_vip ~ attribute_acclimation*attribute_genotype, data = agg_parent_norm_known3, method='eu')

z_pca_vip <- permanova_vip$aov.tab
z_pca_vip
```

#1. Make plots with dots

```{r}
#adding percentages on axis
names(pca_data_vip)[4] <- "PCA1"
names(pca_data_vip)[5] <- "PCA2"
percentage_vip <- round((pca_vip$sdev^2) / sum((pca_vip$sdev^2)) * 100, 2)
percentage_vip <- paste( colnames(pca_data_vip[4:7]), "(", paste(as.character(percentage_vip), "%", ")", sep="") )
```

```{r}
#setting up data to add polygons
pca_data_vip$Acclimation.Genotype <- paste(pca_data_vip$attribute_acclimation, pca_data_vip$attribute_genotype)
find_hull_vip <- function(pca_data_vip) pca_data_vip[chull(pca_data_vip$PCA1, pca_data_vip$PCA2), ]
hulls_vip <- ddply(pca_data_vip, "Acclimation.Genotype", find_hull_vip)
```

```{r}
#add individual sample IDs to dataset
pca_data_vip <- cbind(pca_data_vip, agg_parent_norm_known3$attribute_sample_id)
```

```{r}
#plot points 
PCA_vip1 <- ggplot(pca_data_vip, aes(PCA1, PCA2, color=attribute_acclimation)) + 
  geom_point(size = 4, alpha=0.5, aes(shape = attribute_acclimation)) +
  theme_bw() +
  guides(color=guide_legend(ncol=2)) +
  ylab(percentage_vip[2])+
  xlab(percentage_vip[1])
PCA_vip1
```

```{r}
  geom_text(aes(label = ...9), size = 2.8, nudge_x = 0.2, nudge_y = 0.1)
```

#2. Add centroids
```{r}
#add centroids 
PCAcen_vip <- PCA_vip1 + 
  geom_polygon(data = hulls_vip, alpha = 0.2, aes(color = attribute_acclimation, fill = attribute_acclimation, lty = attribute_acclimation)) +
  geom_point(aes(x=PC1.mean, y=PC2.mean,color=attribute_acclimation, shape = attribute_acclimation), data=pca.centroids.vip, size=4, show.legend=TRUE)
PCAcen_vip
```


```{r}
#select out only top three most important direct parents: 
#x1_pyranosylbenzotriazoles, lineolic_acids_and_derivatives and pentoses
agg_parent_top3 <- agg_parent_norm_known2 %>% dplyr::select(1:5, 33, 47, 58)
View(agg_parent_top3)
```


















































.