---
title: "vip"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
#load required libraries
library(tidyr)
library("reshape")
library(plyr)
library(dplyr)
library(ggplot2)
library("arsenal")
library("Rmisc")
library(gridExtra)
library(ggpubr)
library(factoextra)
library(ggplot2)
library(RColorBrewer)
library(lme4)
library(lmerTest)
library(car)
library(effects)
library(ggfortify)
library(cowplot)
library(vegan)
library(corrr)
library(ggcorrplot)
library(GGally)
library(broom)
library(cowplot)
library(RVAideMemoire)
library(arsenal)
library(patchwork)
library(tidyr)
library(ggrepel)
library(randomForest)
library("janitor")
library(caret)
library(varImp)
```

```{r}
#packages from paper 
library(readxl)
library(cowplot)
library(RColorBrewer)
library(janitor)
library(viridis)
library(vegan)
library(car)
library(magicfor)
library(grid)
library(factoextra)
install.packages("egg")
library(egg)
```

```{r}
#packages not available for R version 4.0.1
install.packages("ropls")
library(ropls)
install.packages("mixOmics")
library("mixOmics")
install.packages("MetaboAnalystR")
library(MetaboAnalystR)
```

#VIP Analysis from paper
```{r}
agg_class_norm_known <- clean_names(agg_class_norm_known)

#random forest analysis from paper 
coral_RF <- randomForest(agg_class_norm_known$attribute_acclimation ~., agg_class_norm_known[ ,c(5:29)], importance = TRUE, ntree = 1000)
VI_class<-caret::varImp(coral_RF)
```

```{r}
#random forest from tutorial
coral_RF <- randomForest(agg_class_norm_known, )
```
#these didn't work for various reasons

#try again with heat_clean2
```{r}
#random forest analysis from paper 
heat_clean3 <- clean_names(heat_clean2)

coral_RF <- randomForest(as.factor(heat_clean3$attribute_acclimation) ~., heat_clean3[ ,c(6:349)], importance = TRUE, ntree = 1000)
VI_all <- caret::varImp(coral_RF)
#there were too many packages: had to specify which varImp
#this made a dataset with too many columns: there should only be one to create the plot
```

```{r}
View(heat_clean3)
```

```{r}
#use dplyr to add another column with all acclimation treatments divided into two groups
heat_clean3 <- heat_clean3 %>% mutate(acclimation2 = 
                         case_when(attribute_acclimation %in% c("1") ~ "A",
                                   attribute_acclimation %in% c("2") ~ "A",
                                   attribute_acclimation %in% c("3") ~ "B",
                                   attribute_acclimation %in% c("4") ~ "B",
                                   attribute_acclimation %in% c("5") ~ "B"))
heat_clean3$acclimation2 <- as.factor(heat_clean3$acclimation2)
```

```{r}
coral_RF2 <- randomForest(heat_clean3$acclimation2 ~., heat_clean3[ ,c(6:349)], importance = TRUE, ntree = 1000)
VI_all2 <- caret::varImp(coral_RF2)
#still creates two columns, but they are identical? so I guess that's fine

#make row names first column
VI_all2$compounds <- row.names(VI_all2)
```

```{r}
write.table(VI_all, "variable_importance_all.xlsx",quote=FALSE,row.names=FALSE,sep="\t")
write.table(VI_class, "variable_importance_class.xlsx",quote=FALSE,row.names=FALSE,sep="\t")
```

#create the figure
```{r}
#code copied from paper
#using all compounds
VIP_all <- left_join(transform(VI_all%>%clean_names()%>%dplyr::rename(molecule=1), molecule=reorder(molecule, -mean_decrease_accuracy))%>%
     head(500)%>%rownames_to_column("n")%>%mutate(n=as.numeric(n))%>%
     separate(molecule,into=c("cluster_id","other"),sep="_",remove=FALSE)%>%
     separate(cluster_id,into=c("trash","cluster_id"),sep=1)%>%select(-other,-trash)%>%
     mutate(cluster_id=as.numeric(cluster_id)),read_xlsx("component_ID.xlsx",sheet="Molecular Families")%>%clean_names()%>%select(cluster_id,molecular_family)%>%mutate(cluster_id=as.numeric(cluster_id)),by="cluster_id")%>%
     mutate(molecular_family=str_to_title(molecular_family))
```

```{r}
#couldn't I just make a bar plot? 
VIP_all2 <- ggplot(VI_all2, aes(x = reorder(compounds, A), y = A)) +
  geom_bar(stat = "identity") +
  coord_flip()
VIP_all2
#okay you can't read this but it techinically worked
```

#okay now do it again with the class data 

```{r}
#use dplyr to add another column with all acclimation treatments divided into two groups
agg_class_norm_known3 <- clean_names(agg_class_norm_known3)
agg_class_norm_known3 <- agg_class_norm_known3 %>% mutate(acclimation2 = 
                         case_when(attribute_acclimation %in% c("1") ~ "A",
                                   attribute_acclimation %in% c("2") ~ "A",
                                   attribute_acclimation %in% c("3") ~ "B",
                                   attribute_acclimation %in% c("4") ~ "B",
                                   attribute_acclimation %in% c("5") ~ "B"))
agg_class_norm_known3$acclimation2 <- as.factor(agg_class_norm_known3$acclimation2)
```

```{r}
#randomForest analysis 
coral_RF_class <- randomForest(agg_class_norm_known3$acclimation2 ~., agg_class_norm_known3[ ,c(5:29)], importance = TRUE, ntree = 1000)
VI_class2<-caret::varImp(coral_RF_class)

#make row names first column
VI_class2$class <- row.names(VI_class2)
View(VI_class2)
```

```{r}
#bar plot
VIP_class2 <- ggplot(VI_class2, aes(x = reorder(class, A), y = A)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw() +
  xlab("Class") + ylab("Variable Importance")
VIP_class2
```

#okay now do it again with the direct parent data 
#group treatments 1-3 as A, 4-5 as B

```{r}
#use dplyr to add another column with all acclimation treatments divided into two groups
agg_parent_norm_known2 <- clean_names(agg_parent_norm_known)
agg_parent_norm_known2 <- agg_parent_norm_known2 %>% mutate(acclimation2 = 
                         case_when(attribute_acclimation %in% c("1") ~ "A",
                                   attribute_acclimation %in% c("2") ~ "A",
                                   attribute_acclimation %in% c("3") ~ "A",
                                   attribute_acclimation %in% c("4") ~ "B",
                                   attribute_acclimation %in% c("5") ~ "B"))
agg_parent_norm_known2$acclimation2 <- as.factor(agg_parent_norm_known2$acclimation2)
```

```{r}
#randomForest analysis 
coral_RF_parent <- randomForest(agg_parent_norm_known2$acclimation2 ~., agg_parent_norm_known2[ ,c(5:57)], importance = TRUE, ntree = 1000)
VI_parent<-caret::varImp(coral_RF_parent)

#make row names first column
VI_parent$parent <- row.names(VI_parent)
View(VI_parent)
```

```{r}
#bar plot
VIP_parent <- ggplot(VI_parent, aes(x = reorder(parent, A), y = A)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw() +
  xlab("Direct Parent") + ylab("Variable Importance")
VIP_parent
```

#VIP R package
```{r}
library("vip")
library(xgboost)  # for fitting GBMs
library(ranger)   # for fitting random forests
library(rpart)    # for fitting CART-like decision trees
```

```{r}
#build the model using 
```

#VIP from Kevin
```{r}

```



















































.